---
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: netkit-datapath
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      io.cilium.datapath/netkit: "true"
  defaults:
    datapath-mode: netkit
