---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-svcs-tls
spec:
  secretName: cluster-svcs-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SVCS_DOMAIN}"
  dnsNames:
    - "${SVCS_DOMAIN}"
    - "*.${SVCS_DOMAIN}"
    - "*.${CLUSTER_SVCS_DOMAIN}"

---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-tls
spec:
  secretName: media-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${MEDIA_DOMAIN}"
  dnsNames:
    - "${MEDIA_DOMAIN}"
    - "*.${MEDIA_DOMAIN}"
    - "*.${CLUSTER_MEDIA_DOMAIN}"
