---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-17a
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-22
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 50Gi
    storageClass: ceph-block
  superuserSecret:
    name: pg-17a-secrets
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 512MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-store
        # Note: serverName version needs to be incremented
        # when recovering from an existing cnpg cluster
        serverName: pg-17a-v1

  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres17-v1
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: garage-store
  #         serverName: *previousCluster
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-17a-backup
spec:
  schedule: "0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: pg-17a
  target: prefer-standby
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
