---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP:=jellystat}-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        JWT_SECRET: "{{ .JELLYSTAT_JWT_SECRET }}"
        POSTGRES_USER: "{{ .JELLYSTAT_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .JELLYSTAT_POSTGRES_PASS }}"
        JS_GEOLITE_ACCOUNT_ID: "{{ .JELLYSTAT_GEOLITE_ACCOUNT_ID }}"
        JS_GEOLITE_LICENSE_KEY: "{{ .JELLYSTAT_GEOLITE_LICENSE_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: ${APP:=jellystat}
        INIT_POSTGRES_HOST: pg-17a-rw.db.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .JELLYSTAT_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .JELLYSTAT_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: ${APP:=jellystat}-${CLUSTER_NAME}
    - extract:
        key: cloudnative-pg-${CLUSTER_NAME}
