---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unpackerr-secret
    template:
      data:
        UN_SONARR_0_URL: "http://sonarr.media.svc.cluster.local"
        UN_SONARR_0_API_KEY: "{{ .sonarr_api_key }}"
        UN_RADARR_0_URL: "http://radarr.media.svc.cluster.local"
        UN_RADARR_0_API_KEY: "{{ .radarr_api_key }}"
  dataFrom:
    - extract:
        key: sonarr-${CLUSTER_NAME}
      rewrite:
        - regexp:
            source: "api_key"
            target: "sonarr_api_key"
    - extract:
        key: radarr-${CLUSTER_NAME}
      rewrite:
        - regexp:
            source: "api_key"
            target: "radarr_api_key"
