apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cluster-info
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  CLUSTER_NAME: "fairy-k8s01"
  CLUSTER_DOMAIN: "fairy.freckle.systems"
  CLUSTER_SVCS_DOMAIN: "fairy.freckle.services"
