apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-k8s-cluster-secrets
  annotations:
    policies.kyverno.io/title: Sync K8s Cluster Secrets
    policies.kyverno.io/category: Cluster Info Sync
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy will copy a Secret called `k8s-cluster-secrets` from the `default`
      Namespace to new Namespaces when they are created. It will also push
      updates to the copied Secret should the source Secret be changed.

spec:
  rules:
    - name: sync-k8s-cluster-secrets
      match:
        any:
          - resources:
              kinds:
                - Namespace
      generate:
        apiVersion: v1
        kind: Secret
        name: k8s-cluster-secrets
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: default
          name: k8s-cluster-secrets
