---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./certificates.yaml
  - ./gw-external.yaml
  - ./gw-internal.yaml
  - ./gw-media-mgmt.yaml
  - ./gw-media-public.yaml
  - ./gw-media.yaml
  - ./gw-tailscale.yaml
  - ./redirect.yaml
