---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-server-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # WireGuard keys
        WG_PRIVATE_KEY: "{{ .private_key }}"
        WG_PEER_ATLANTIS_PUBKEY: "{{ .peer_atlantis_pubkey }}"
        WG_PEER_ATLANTIS_PSK: "{{ .peer_atlantis_psk }}"
        # Network configuration
        WAN_INTERFACE: "enp1s0f0"
        PUBLIC_IPV6_PREFIX: "{{ .public_ipv6_prefix }}"
  dataFrom:
    - extract:
        key: wg-server
