---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/flux-post-build-variables
resources:
  - ./default
  - ./envoy-gateway-system
  - ./external-secrets
  - ./flux-system
  - ./kube-system
  - ./tailscale
  - ./wg/ks.yaml
