---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: wg-routers
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "wg-routers",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br0",
          "vlan": 200,
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
