# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-system
  - ./cert-manager
  - ./db
  - ./external-dns
  - ./external-secrets
  - ./flux-system
  - ./freckle-id
  - ./gateway
  - ./it-tools
  - ./kube-system
  - ./media
  - ./observability
  - ./rook-ceph
  - ./security
  - ./spegel
  - ./system-upgrade
  - ./tailscale
