---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuwunel
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  interval: 1h
  values:
    controllers:
      tuwunel:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/matrix-construct/tuwunel
              tag: v1.4.8@sha256:0e4a55713e5b2bbcae1c9d120395f502fc96bb546c0da589aa87e2c561c6e2f4
            env:
              - name: TUWUNEL_SERVER_NAME
                value: ${CHAT_DOMAIN}
              - name: TOKIO_WORKER_THREADS
                value: "5"
              - name: TUWUNEL_ROCKSDB_PARALLELISM_THREADS
                value: "4"
              - name: TUWUNEL_DATABASE_PATH
                value: "/data/db"
              - name: TUWUNEL_DATABASE_BACKEND
                value: "rocksdb"
              - name: TUWUNEL_ADDRESS
                value: "0.0.0.0"
              - name: TUWUNEL_PORT
                value: "8080"
              - name: RUST_LOG
                value: "info"
              - name: TUWUNEL_ALLOW_FEDERATION
                value: "true"
              - name: TUWUNEL_ALLOW_REGISTRATION
                value: "true"
              - name: TUWUNEL_TRUSTED_SERVERS
                value: '["matrix.org"]'
              - name: TUWUNEL_WELL_KNOWN__CLIENT
                value: https://matrix.${CHAT_DOMAIN}
              - name: TUWUNEL_WELL_KNOWN__SERVER
                value: "matrix.${CHAT_DOMAIN}:443"
              - name: TUWUNEL_MAX_REQUEST_SIZE
                value: "104857600"
              - name: TUWUNEL_IP_LOOKUP_STRATEGY
                value: "5"
            envFrom:
              - secretRef:
                  name: tuwunel-secret
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /_matrix/federation/v1/version
                    port: http
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

    service:
      main:
        ports:
          http:
            port: &port 80
            protocol: TCP
            targetPort: 8080
    route:
      matrix:
        annotations: {}
        labels: {}
        hostnames:
          - "matrix.${CHAT_DOMAIN}"
        parentRefs:
          - name: envoy-public
            namespace: gateway-system
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /_matrix
            backendRefs:
              - identifier: main
                port: *port
      app:
        annotations: {}
        labels: {}
        hostnames:
          - "${CHAT_DOMAIN}"
        parentRefs:
          - name: envoy-public
            namespace: gateway-system
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /.well-known/matrix
            backendRefs:
              - identifier: main
                port: *port
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        retain: true
        suffix: "data"
        advancedMounts:
          tuwunel:
            app:
              - path: /data
