---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloaders
components:
  - ../../../../components/flux-post-build-variables
resources:
  - ./cnp-default-egress.yaml
  - ./pvc-store01.yaml
  - ./qbt-ink.yaml
  - ./qbt-reel.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
