---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloaders-store01-downloads
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  claimRef:
    name: store01-downloads
    namespace: downloaders
  nfs:
    path: /mnt/store01/warehouse20/media/downloads
    server: 172.25.2.4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store01-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: downloaders-store01-downloads
