---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hookshot
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  interval: 1h
  values:
    controllers:
      hookshot:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/matrix-org/matrix-hookshot
              tag: 7.3.2@sha256:240079c3c57b35d5c1f1fef67bcccd7717fffac543d9fc64b04bec60d0c59902
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            # probes:
            #   liveness:
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /metrics
            #         port: 9001
            #       initialDelaySeconds: 10
            #       periodSeconds: 30
            #       timeoutSeconds: 5
            #       failureThreshold: 3
            #   readiness:
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /metrics
            #         port: 9001
            #       initialDelaySeconds: 5
            #       periodSeconds: 10
            #       timeoutSeconds: 5
            #       failureThreshold: 3

    service:
      appservice:
        controller: hookshot
        ports:
          http:
            port: 80
            targetPort: 9993
      webhooks:
        controller: hookshot
        ports:
          http:
            port: 80
            targetPort: 9000
      metrics:
        controller: hookshot
        ports:
          http:
            port: 80
            targetPort: 9001

    route:
      webhooks:
        hostnames:
          - "hookshot.${CHAT_DOMAIN}"
        parentRefs:
          - name: envoy-public
            namespace: gateway-system
        rules:
          - backendRefs:
              - name: hookshot-webhooks
                port: 80

    persistence:
      config:
        type: secret
        name: hookshot-config
        globalMounts:
          - path: /data/config.yml
            subPath: config.yml
          - path: /data/registration.yml
            subPath: registration.yml
          - path: /data/passkey.pem
            subPath: passkey.pem
