---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-status
spec:
  providerRef:
    name: github-status
  eventMetadata:
    cluster: ${CLUSTER_NAME}
  eventSources:
    - kind: Kustomization
      name: "*"
