---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frr
  namespace: wg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: frr
          image: quay.io/frrouting/frr:10.5.0@sha256:fc7f887ab4d8da06f481a4f8d59afded88b3c5823f03610a7e808f7eba45eeea
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: frr-config
              mountPath: /etc/frr/frr.conf
              subPath: frr.conf
              readOnly: true
            - name: frr-config
              mountPath: /etc/frr/daemons
              subPath: daemons
              readOnly: true
            - name: frr-config
              mountPath: /etc/frr/vtysh.conf
              subPath: vtysh.conf
              readOnly: true
      volumes:
        - name: frr-config
          configMap:
            name: frr-config
