---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-server
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  interval: 1h
  values:
    controllers:
      wg-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/wireguard
              tag: 1.0.20250521@sha256:14d1da065306c97d0a7171901221027dcbaa4be6c8731a3d8bdc54d57a92bbfe
            env:
              TZ: America/Chicago
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            ports:
              - name: wireguard
                containerPort: 51820
                hostPort: 51820
                protocol: UDP
              - name: qbt-tcp
                containerPort: 50469
                hostPort: 50469
                protocol: TCP
              - name: qbt-udp
                containerPort: 50469
                hostPort: 50469
                protocol: UDP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        sysctls:
          - name: net.ipv6.conf.all.forwarding
            value: "1"
    persistence:
      wg-config:
        type: secret
        name: wg-server-secrets
        globalMounts:
          - path: /config/wg_confs/wg0.conf
            subPath: wg0.conf
            readOnly: true
