---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wg-server-3
  namespace: &namespace wg
  labels:
    infra.freckle.systems/post-build-variables: enabled
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/networking/wireguard
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        - op: replace
          path: /metadata/name
          value: wg-server-3

        # Server uses hostNetwork (no LoadBalancer available)
        - op: add
          path: /spec/values/defaultPodOptions/hostNetwork
          value: true

        # Remove the config PVC (not needed)
        - op: remove
          path: /spec/values/persistence/config

        # Use our config secret
        - op: replace
          path: /spec/values/persistence/wg-config/name
          value: wg-server-3-secrets

        # Use wg2 interface
        - op: replace
          path: /spec/values/persistence/wg-config/globalMounts
          value:
            - path: /config/wg_confs/wg2.conf
              subPath: wg2.conf
              readOnly: true
