---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
components:
  # - ../../../../components/common
  - ../../../../components/flux-post-build-variables
resources:
  - ./external-secrets.yaml
  - ./onepassword-connect.yaml
