---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app onepassword-connect
  namespace: &namespace external-secrets
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: *namespace
  path: ./kubernetes/apps/secrets/onepassword/connect
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 5m

---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app onepassword-store
  namespace: &namespace external-secrets
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
  targetNamespace: *namespace
  path: ./kubernetes/apps/secrets/onepassword/store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  timeout: 5m
  patches:
    - target:
        kind: ClusterSecretStore
        name: onepassword
      patch: |-
        - op: replace
          path: /spec/provider/onepassword/vaults
          value:
            kube-tortuga: 1
