apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-cluster-info
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  CLUSTER_NAME: "atlantis-k8s01"
  CLUSTER_DOMAIN: "atlantis.freckle.systems"
  CLUSTER_SVCS_DOMAIN: "atlantis.freckle.services"
  GARAGE_S3_REGION: "us-den1"
