---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../../../components/flux-post-build-variables
resources:
  - ./app-template.yaml
  - ./es-cluster-domains.yaml
  - ./namespace.yaml
