---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP:=streamystats}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        DATABASE_URL: "postgresql://{{ .STREAMYSTATS_POSTGRES_USER }}:{{ .STREAMYSTATS_POSTGRES_PASS }}@pg-17a-rw.db.svc.cluster.local:5432/${APP:=streamystats}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: ${APP:=streamystats}
        INIT_POSTGRES_HOST: pg-17a-rw.db.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .STREAMYSTATS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .STREAMYSTATS_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: ${APP:=streamystats}-${CLUSTER_NAME}
    - extract:
        key: pg-17a-${CLUSTER_NAME}
