---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tuppr-plans
  namespace: &namespace system-upgrade
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: tuppr
      namespace: system-upgrade
  interval: 1h
  path: ./kubernetes/apps/system-upgrade/plans
  postBuild:
    substitute:
      # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
      KUBERNETES_VERSION: v1.34.3
      # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
      TALOS_VERSION: v1.12.4
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
