---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br0",
          "vlan": 201,
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "192.168.66.1"},
              {"dst": "::/0", "gw": "fe80::201:def"}
            ]
          }
        }
      ]
    }
