---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: webhook-secrets
    template:
      data:
        SONARR_API_KEY: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: sonarr-${CLUSTER_NAME}
