---
ingress:
  - hostname: ingress.${CLUSTER_DOMAIN}
    originRequest:
      originServerName: ingress.${CLUSTER_DOMAIN}
      http2Origin: true
    service: https://envoy-public.gateway-system.svc.cluster.local:443
  - service: http_status:404
